[package]
name = "helloworld"
version = "0.1.0"
authors = ["Naoki Numaguchi <naoki.numaguchi@groove-x.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
